# Generated by Django 5.0 on 2024-05-17 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='closing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
