# Generated by Django 5.0 on 2024-05-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_jobposting_logo_jobposting_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('required_knowledge', models.TextField(max_length=2000)),
                ('education_experience', models.TextField(max_length=2000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchApp.jobposting')),
            ],
        ),
    ]
