# Generated by Django 5.0 on 2024-05-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company_info',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company_web',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
