# Generated by Django 5.0 on 2024-05-19 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0005_jobposting_company_email_jobposting_company_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='lga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='year_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('INTERVIEW', 'Interview'), ('EMPLOYED', 'Employed')], max_length=255, null=True),
        ),
    ]
