# Generated by Django 5.0 on 2024-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0006_jobapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
    ]
