# Generated by Django 5.0 on 2024-05-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0007_alter_jobposting_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
